api_id: 21781076 # This has to be an integer. Read more [here](https://core.telegram.org/api/obtaining_api_id)
api_hash: 'b0a0bb1f8b27d53a9d5f617fc2c9d19d' # Long 32 characters hash identifier. Read more [here](https://core.telegram.org/api/obtaining_api_id)
session_name: 'forwardgram' # # Session name. Only one session (with a unique session name) can run at a time
phone: '+6584342498'

# The channel names that you'd like to forward messages from.
# The user running the client must have these channels present on it's dialogs.
input_channel_names:
  - 'Channel Name A'
  - 'Channel Name B'

# The output channel names that the messages will be forwarded to.
# The user running the client must have a write access to those channels, and have the channels present on theirs dialogs.
output_channel_name: 'My Cool Channel Name'